version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management interface
    labels:
      NAME: "rabbitmq"

  client_api:
    build:
      context: . # The context is the root of the monorepo
      dockerfile: Dockerfile
      args:
        PACKAGE_NAME: client_api
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    labels:
      NAME: "client_api"
    ports:
      - "3000:3000"
  conversation_api:
    build:
      context: ./packages/conversation_api
      dockerfile: Dockerfile
      args:
        PACKAGE_NAME: conversation_api
    labels:
      NAME: "conversation_api"
    ports:
      - "3001:3001"
    volumes:
      - ./packages/conversation_api:/app

  chat_expert:
    build:
      context: . # The context is the root of the monorepo
      dockerfile: Dockerfile
      args:
        PACKAGE_NAME: chat_expert
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    labels:
      NAME: "chat_expert"
  manager_expert:
    build:
      context: . # The context is the root of the monorepo
      dockerfile: Dockerfile
      args:
        PACKAGE_NAME: manager_expert
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    labels:
      NAME: "manager_expert"
  expense_tracking_expert:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE_NAME: expense_tracking_expert
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    labels:
      NAME: "expense_tracking_expert"

  savings_expert:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE_NAME: savings_expert
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    labels:
      NAME: "savings_expert"
