version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management interface
    labels:
      NAME: "rabbitmq"

  expense_tracking_expert:
    build: ./expense_tracking_expert
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    labels:
      NAME: "expense_tracking_expert"

  savings_expert:
    build: ./savings_expert
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    labels:
      NAME: "savings_expert"
